version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: '11:00'
  labels:
  - dependencies
  commit-message:
    prefix: deps

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: '11:00'
  commit-message:
    prefix: ci
